### ISSUE TITLE
Could not find a version that satisfies the requirement ctypes

### ISSUE THREAD

**Issue by IslaFTW** [zeyad-mansour/Lunar#1]
When I install the requisiments.txt, in the end I get this error:

```
ERROR: Could not find a version that satisfies the requirement ctypes
ERROR: No matching distribution found for ctypes
```

![2021-04-28 03_53_08-Fortnite](https://user-images.githubusercontent.com/60049112/116392675-8ec3c780-a7d5-11eb-9d3e-fde0d5650b4e.png)

Even so, I open the program perfectly, but when the game starts and a character appears in front of me, it closes and shows the following error

![2021-04-28 03_54_48-Símbolo del sistema](https://user-images.githubusercontent.com/60049112/116392950-ee21d780-a7d5-11eb-928b-e26ef17b2b38.png)

btw: i Send you a private message on twitter, you may be interested

**Comment by 0xmmalik** [comment]
You don't need to install `ctypes` from pip. It's an included Python package. Because this is the case, it should also be removed from the `requirements.txt` file.

**Comment by IslaFTW** [comment]
> You don't need to install `ctypes` from pip. It's an included Python package. Because this is the case, it should also be removed from the `requirements.txt` file. I've made a pull request that fixes that. #2 @zeyad-mansour

THX, You know, any solution to the second error that I get?

**Comment by 0xmmalik** [comment]
Both errors mean the same thing.

**Comment by IslaFTW** [comment]
> Both errors mean the same thing.

I mean, the error where everything works perfectly, but in the moment where some character appears in front of me, the "Lunar" program closes and does not work

This:
![2021-04-28 03_54_48-Símbolo del sistema](https://user-images.githubusercontent.com/60049112/116453468-c7829180-a813-11eb-945e-9ee8e05506cc.png)

**Comment by zeyad-mansour** [comment]
Thanks for opening an issue. I'll update the repository shortly to

**Comment by 0xmmalik** [comment]
That's a separate problem for which you should open a second issue.

**Comment by zeyad-mansour** [comment]
Thanks for opening an issue. @0xmmalik is correct that `ctypes ` should not be included in the requirements file. I have updated that. 

Also, in regard to the second error that you received, try pulling the repository again and see if you still encounter an error. If you do, please reply and attach a screenshot of it.

**Comment by IslaFTW** [comment]
> Thanks for opening an issue. @0xmmalik is correct that `ctypes` should not be included in the requirements file. I have updated that.
> 
> Also, in regard to the second error that you received, try pulling the repository again and see if you still encounter an error. If you do, please reply and attach a screenshot of it.

I just downloaded the new version, and when installing the requirements.txt I get this error:

> ERROR: Could not find a version that satisfies the requirement timeit
> ERROR: No matching distribution found for timeit

![2021-04-28 11_49_16-Símbolo del sistema](https://user-images.githubusercontent.com/60049112/116457072-d1a68f00-a817-11eb-98db-d9a8dcf2b933.png)

**Comment by zeyad-mansour** [comment]
Sorry about that. Removing `timeit` from the requirements.txt file or pulling one more time should resolve that error.

**Comment by Oleja27** [comment]
Can you give commands to fix the problem?
