### ISSUE TITLE
AMD GPUs

### ISSUE THREAD

**Issue by rmilejcz** [zeyad-mansour/Lunar#10]
Do you think this would work at all without CUDA? I know you mention that performance will suffer without it, but is it worth trying without using an NVIDIA card?

**Comment by zeyad-mansour** [comment]
An NVIDIA card is required to use the GPU, otherwise the CPU will be used. You'll get around 15 FPS depending on your CPU, which isn't great, but still may be practical to use.
btw I'll be pushing the repo soon to improve on the player tracking, which currently has some problems.

**Comment by rmilejcz** [comment]
yeah I tried it, could only get around 2-5 FPS on my Ryzen 3600 unfortunately.

Any plans to support OpenCL? Tbh it doesn't look doable without some serious legwork since pytorch doesn't support it, would be cool though
