### ISSUE TITLE
Players are not detected

### ISSUE THREAD

**Issue by bacalado** [zeyad-mansour/Lunar#11]
In the program it says that cuda is active but then in lunar vision it does not detect the players.
I do not get the picture that marking the player

**Comment by zeyad-mansour** [comment]
I would need an image or a better description to understand this issue.

**Comment by anonio100** [comment]
- 

https://user-images.githubusercontent.com/83074513/121252966-e52e2680-c8a8-11eb-881d-44c2e32f1d6c.mp4
![C__WINDOWS_py exe 08_06_2021 22_27_02](https://user-images.githubusercontent.com/83074513/121253118-05f67c00-c8a9-11eb-9130-d709c9b98f33.png)

**Comment by bacalado** [comment]
https://user-images.githubusercontent.com/85557738/121253331-47872700-c8a9-11eb-989a-737827e3424a.mp4

**Comment by zeyad-mansour** [comment]
Not sure why that is happening. Trying pulling the repo again and run that.
