### ISSUE TITLE
just targeting not locked!

### ISSUE THREAD

**Issue by amir-noroozi** [zeyad-mansour/lunar#115]
pls help me aim bot is run but the aim bot is not locked head just type targeting
[This Video](https://s6.uupload.ir/filelink/gXscs58mnZH6_e727d3171b/s_fi28.mp4)

**Comment by TonttuHomo** [comment]
Press F1 to start Aimbot

**Comment by amir-noroozi** [comment]
aim bot is run with f1 but dont locked head !!!!!

**Comment by TonttuHomo** [comment]
Okay, umm. Have you installed all the depensies?

**Comment by amir-noroozi** [comment]
pls help me to set defualt x-y and targeting sensevity

**Comment by amir-noroozi** [comment]
> Okay, umm. Have you installed all the depensies?

do you have discord ? 
i show live for you

**Comment by TonttuHomo** [comment]
Youncan find them in the Fortnite settings

**Comment by TonttuHomo** [comment]
Ohh you are in gta

**Comment by TonttuHomo** [comment]
GTA probably does not allow for external mouse movement since this is for Fortnite specifically

**Comment by amir-noroozi** [comment]
> Ohh you are in gta

some person use this aim bot in fivem
and get pay from this sourse !

**Comment by TonttuHomo** [comment]
Im not familiar how Gta uses mouse input and if you can change it. Try to look for raw mouse input in the settings and disable it if possible.

**Comment by amir-noroozi** [comment]
> Im not familiar how Gta uses mouse input and if you can change it. Try to look for raw mouse input in the settings and disable it if possible.

do you have discord ?

**Comment by TonttuHomo** [comment]
Im at school right now and as I said im not familiar how Gta utilises your mouse. Try to google for gta aimbot sources and you can see what mouse movement type it uses.

**Comment by TonttuHomo** [comment]
I just know that this does not work for the most new games

**Comment by amir-noroozi** [comment]
> I just know that this does not work for the most new games



> Im at school right now and as I said im not familiar how Gta utilises your mouse. Try to google for gta aimbot sources and you can see what mouse movement type it uses.

a lot of people run this source in the gta and dont have proplem

**Comment by TonttuHomo** [comment]
Try to redownload and disable anti-virus since it can mees up the code.

**Comment by amir-noroozi** [comment]
> Try to redownload and disable anti-virus since it can mees up the code.

ok and this work from windows 11 ?

**Comment by TonttuHomo** [comment]
Yes it does its just a little slow and needs a beefy gpu

**Comment by amir-noroozi** [comment]
> 

ok thanks

**Comment by TonttuHomo** [comment]
No problem

**Comment by TonttuHomo** [comment]
Oh one more thing. If you dont press right mouse it does not lock, ot needs to aim to lock. Thats why its only targetting.

**Comment by amir-noroozi** [comment]
> Oh one more thing. If you dont press right mouse it does not lock, ot needs to aim to lock. Thats why its only targetting.

ok pls wait

**Comment by amir-noroozi** [comment]
i try it and not click right mouse but when i shooting  not locked just type targeting and my crosshair on player head

**Comment by amir-noroozi** [comment]
> i try it and not click right mouse but when i shooting not locked just type targeting and my crosshair on player head

![Uploading image.png…]()

**Comment by TonttuHomo** [comment]
Image does not work, please reupload

**Comment by amir-noroozi** [comment]
> Image does not work, please reupload

![image](https://user-images.githubusercontent.com/45897142/156167298-d83611b5-aa60-4bdd-b920-59502e3a44a5.png)

**Comment by TonttuHomo** [comment]
Try opening Cmd in the windows search bar, the type python there and after that import win32api and tell if any errors

**Comment by amir-noroozi** [comment]
> Try opening Cmd in the windows search bar, the type python there and after that import win32api and tell if any errors

not have error
![image](https://user-images.githubusercontent.com/45897142/156167585-3d6376ff-608a-4ef2-83c6-87f5d02d4411.png)

**Comment by TonttuHomo** [comment]
Its probably because of FiveM, they have made the encryption better or blocks any other mouse input like Valorant does.

**Comment by TonttuHomo** [comment]
You need to bypass the anticheat or something. Google it up since I dont know how to do that.

**Comment by amir-noroozi** [comment]
i import lib but have yellow underline
![image](https://user-images.githubusercontent.com/45897142/156167863-728f70a6-0466-45a7-bdeb-4d5da30cb519.png)

**Comment by TonttuHomo** [comment]
Try to run a debug it could help

**Comment by amir-noroozi** [comment]
> What did you enter for the sensitivity? It can be found in the config

i not now i need help bro when you can come to discord ?
l show you in the live

**Comment by amir-noroozi** [comment]
> Try to run a debug it could help

![image](https://user-images.githubusercontent.com/45897142/156168339-efcc6d4e-b7d7-4028-b861-9c96f116921f.png)

**Comment by TonttuHomo** [comment]
go to the command line and run pip install pynput

**Comment by amir-noroozi** [comment]
> go to the command line and run pip install pynput

![image](https://user-images.githubusercontent.com/45897142/156168530-b8f9d072-7dd2-4560-a04c-6a7a33a4ed64.png)

**Comment by TonttuHomo** [comment]
Im not using the same code editor but does it have internal terminal

**Comment by TonttuHomo** [comment]
I use pycharm which has terminal build in so it install everything in the same place and makes importing easier

**Comment by TonttuHomo** [comment]
Do pip uninstall pynput and install it in again in the pycharm

**Comment by amir-noroozi** [comment]
> Do pip uninstall pynput and install it in again in the pycharm

ok

**Comment by amir-noroozi** [comment]
![image](https://user-images.githubusercontent.com/45897142/156169041-abef67e2-e007-46e6-b6c2-c0bec416d4d5.png)

**Comment by TonttuHomo** [comment]
Install a different version and itt should work fine

**Comment by TonttuHomo** [comment]
Have you updated your pip?

**Comment by amir-noroozi** [comment]
> Install a different version and itt should work fine

ok pls wait bro

**Comment by TonttuHomo** [comment]
What GPU do you have?

**Comment by amir-noroozi** [comment]
> What GPU do you have?

mx150 4GB

**Comment by TonttuHomo** [comment]
Is it Nvidia card

**Comment by TonttuHomo** [comment]
Okay. Heres the deal. Your Gpu looks that it does not support CUDA. Which is needed for this. I found that it could affect the locking of the aimbot and make it not work. Since the hack is bad at utilising opengl.

**Comment by amir-noroozi** [comment]
> Is it Nvidia card

yes

**Comment by TonttuHomo** [comment]
It can work but it will be tricky since I dont have any knowledge of this category of problems.

**Comment by TonttuHomo** [comment]
No, as it says in the description it does not work with 16 series of nvidia card yet

**Comment by amir-noroozi** [comment]
> 



> No, as it says in the description it does not work with 16 series of nvidia card yet

why ?

**Comment by TonttuHomo** [comment]
I have rtx series of Nvidia cards so its compatible with them atleast. I have no idea why it does not work with the 16 series cards. Maybe something to do with the different CUDA utilising type.

**Comment by amir-noroozi** [comment]
> I have rtx series of Nvidia cards so its compatible with them atleast. I have no idea why it does not work with the 16 series cards. Maybe something to do with the different CUDA utilising type.

can you give me your discord id ?

**Comment by TonttuHomo** [comment]
There is a known issue that occurs with PyTorch and the GeForce 16 series GPUs on Windows. Unfortunately, if you are using one of these GPUs, the aimbot will not work for you.

Found this

**Comment by amir-noroozi** [comment]
> There is a known issue that occurs with PyTorch and the GeForce 16 series GPUs on Windows. Unfortunately, if you are using one of these GPUs, the aimbot will not work for you.
> 
> Found this

ok pls wait

**Comment by TonttuHomo** [comment]
https://github.com/zeyad-mansour/lunar/issues/98 There they have a conversation of this topic, go there and ask if the ways there does not work.
