### ISSUE TITLE
16 SERIES AND DETECT

### ISSUE THREAD

**Issue by zMasterITA123** [zeyad-mansour/lunar#125]
I saw that the files are changed 4 days ago and i have 2 questions, the gpu 16 series now work with aim assist? and second is it detected now? because i saw that is messes with files now

**Comment by TonttuHomo** [comment]
It is not

**Comment by zMasterITA123** [comment]
> It is not

did you tested it? because i dont want to be banned again

**Comment by FardMan69420** [comment]
Again? Fortnite doesnt have an anticheat for these kind of aimbots

**Comment by TonttuHomo** [comment]
It is NOT detected. Thats it thanks
