### ISSUE TITLE
how to get proper training data

### ISSUE THREAD

**Issue by dorian-gabIer** [zeyad-mansour/lunar#134]
how to get proper training data

**Comment by ZCban** [comment]
if you mean another game you have to create a database of images as vast as possible and train ai but the procedure is long and complex I tried with rust to make a custom it works but not 100% also due to the sensitivity

**Comment by dorian-gabIer** [comment]
> if you mean another game you have to create a database of images as vast as possible and train ai but the procedure is long and complex I tried with rust to make a custom it works but not 100% also due to the sensitivity

I meant for fortnite. The dataset are only the files located in lib/data?

**Comment by ZCban** [comment]
best.pt is the trained file serch for yolo training

**Comment by ZCban** [comment]
non ho capito cosa stai dicendo,in questo progetto che scarichi non ci sono immagini jpg le immagini sono racchiuse in best.pt che è un file che viene creato quando rielabora le immagini per fare l allenamento in pratica lì dentro stanno le immagini con i box per i target ma è un file che viene creato da un altro programma che legge le immagini che vai a inserire e modificare per yolo cerca su google yolo allenamento custom

**Comment by ZCban** [comment]
I did not understand what you are saying, in this project you download there are no jpg images the images are enclosed in best.pt which is a file that is created when reprocessing the images to do the training in practice there are the images with the boxes for the targets but it is a file that is created by another program that reads the images that you go to insert and modify for yolo search on google yolo custom training
