### ISSUE TITLE
Activate aimbot on left mouse button

### ISSUE THREAD

**Issue by isvktt** [zeyad-mansour/Lunar#14]
How do I activate the aimbot only when I press the left mouse button?

**Comment by zeyad-mansour** [comment]
If you want to do that, you would need to change [this](https://github.com/zeyad-mansour/Lunar/blob/363f73b757259bbf31fdb93d30f6bea9367b3ef6/lib/aimbot.py#L165) to
`targeted = True if win32api.GetKeyState(0x01) in (-127, -128) else False #checks if left mouse button is being held down`
