### ISSUE TITLE
0 FPS

### ISSUE THREAD

**Issue by igorgiraffa** [zeyad-mansour/Lunar#16]
pls im new on this and i really love the prject but the lunar vision stays at 0 fps how can i fix this ? 0 fps makes that the aimbot dont work

**Comment by zeyad-mansour** [comment]
What GPU does your computer have?

**Comment by igorgiraffa** [comment]
> What GPU does your computer have?
GTX 550 TI

**Comment by igorgiraffa** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/43867853/122305613-95b9ad00-cedd-11eb-9a39-56efb34c9739.png)

**Comment by igorgiraffa** [comment]
![Screenshot_8](https://user-images.githubusercontent.com/43867853/122306899-ab2fd680-cedf-11eb-906d-867b1b2348fc.png)

**Comment by zeyad-mansour** [comment]
Yes, that's the reason. Unfortunately, a GTX 1050ti at minimum is required to use your NVIDIA graphics card.

**Comment by igorgiraffa** [comment]
> Yes, that's the reason. Unfortunately, a GTX 1050ti at minimum is required to use your NVIDIA graphics card.

i seen other program that looks like urs that uses Open CL when there is no cuda , can lunar do this ?? or i should wait until u upade lunar ?

**Comment by isvktt** [comment]
it would be a good idea to make it work in OpenCL when there is no CUDA
