### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by qExoticBalls** [zeyad-mansour/Lunar#18]
I dont know why every time I try running the python script it says ModuleNotFoundError: No module named 'cv2'

Im using CMD to run the script (by stating the scripts directory and using the python keyword to get python to run in cmd) but it still doesnt work. any tips?

**Comment by zeyad-mansour** [comment]
You need to run `pip install -r requirements.txt`

Also, you don't need to run your python scripts in a specific directory, since you should add it to PATH during installation.
