### ISSUE TITLE
the aim is jumping

### ISSUE THREAD

**Issue by islamyasereq** [zeyad-mansour/Lunar#19]
so when i aim the crosshair is jumping from location to another location randomly, it should be aimed at the closest target

**Comment by islamyasereq** [comment]
sometimes the aiimobt is aiming at the guns

**Comment by islamyasereq** [comment]
and if you can add triggerbot

**Comment by zeyad-mansour** [comment]
> so when i aim the crosshair is jumping from location to another location randomly, it should be aimed at the closest target

It currently aims at detection with the greatest confidence in the frame. I'll change it so that it aims at the object that's closest to the crosshair when in the next update.

**Comment by zeyad-mansour** [comment]
> sometimes the aiimobt is aiming at the guns

What do you mean? Could you attach an example or clarify?

**Comment by zeyad-mansour** [comment]
> and if you can add triggerbot

Yes. Later.

**Comment by islamyasereq** [comment]
> > so when i aim the crosshair is jumping from location to another location randomly, it should be aimed at the closest target
> 
> It currently aims at detection with the greatest confidence in the frame. I'll change it so that it aims at the object that's closest to the crosshair when in the next update.

cool cuz where there 2 targets in the screen the aim is jumping between them like it is confused which one to target, if you get what I mean

**Comment by islamyasereq** [comment]
> > sometimes the aiimobt is aiming at the guns
> 
> What do you mean? Could you attach an example or clarify?

sorry it was cuz of the resolution

**Comment by yttiby** [comment]
Is this now fixed?

**Comment by zeyad-mansour** [comment]
Yeah, that's why I closed the issue.
