### ISSUE TITLE
its trojan 

### ISSUE THREAD

**Issue by GoodBoyLikeGod** [zeyad-mansour/Lunar#22]
windows defender saying trojan

**Comment by zeyad-mansour** [comment]
Please refrain from opening duplicate issues.

Attach an image or a better description of the error that you are receiving.

**Comment by GoodBoyLikeGod** [comment]
WINDOWS DEFENDER SAY trojan 64 x

**Comment by GoodBoyLikeGod** [comment]
its isnt trojan its from x ray to minecraft XDDDDDDD sorry

**Comment by Fidode07** [comment]
It's not a Trojan. Everyone who can Python (Me Included) can read this and see it isnt.
