### ISSUE TITLE
Im having an issue with the startup I also ran pip install -r requirements.txt

### ISSUE THREAD

**Issue by Ruskifps** [zeyad-mansour/Lunar#23]
![cap](https://user-images.githubusercontent.com/86194500/122676843-bfa8f300-d1ad-11eb-851b-c0f17aac2938.PNG)

**Comment by zeyad-mansour** [comment]
That's weird. Try running `pip install scipy`

**Comment by zeyad-mansour** [comment]
I just realized that `scipy` is an extraneous import anyway. I forgot to remove it since I had used it previously. Try pulling again.
