### ISSUE TITLE
What should be inside the config file?

### ISSUE THREAD

**Issue by algerr** [zeyad-mansour/Lunar#24]
In line 79 of the aimbot.py the config json file opens but since I do not know what it should contain, there cannot be any data extracted from it. I would appreciate an explainable reply.

**Comment by zeyad-mansour** [comment]
If you run lunar.py for the first time, you'll find out. It simply contains your sensitivity settings. For example:

![image](https://user-images.githubusercontent.com/45726273/122805612-50a7c900-d297-11eb-83fb-471e62d8ba70.png)

As described in the [README](https://github.com/zeyad-mansour/Lunar#usage), if you want to update your sensitivity settings again, run:  `python lunar.py setup`
