### ISSUE TITLE
No detecting player

### ISSUE THREAD

**Issue by qwertyplm** [zeyad-mansour/Lunar#25]
I installed all the things and followed the tutorial but the program doesn't detect the players

**Comment by zeyad-mansour** [comment]
Do you mean that no bounding boxes are being drawn? What FPS are you getting?

**Comment by qwertyplm** [comment]
No bounding boxes are being drawn and the aimbot doesn't work. I get around 20 fps

**Comment by zeyad-mansour** [comment]
Please attach an example of this.

**Comment by qwertyplm** [comment]
Its hard for me to take a video now but i can attach a video from another user that have my same problem 


https://user-images.githubusercontent.com/85174026/122812361-1c490280-d2c1-11eb-879f-b4a0aa684cc2.mp4

**Comment by zeyad-mansour** [comment]
That's strange. Try running [this](https://gist.github.com/zeyad-mansour/de4e4c269ad624bcf8b801e905f14993) and paste the results.

**Comment by qwertyplm** [comment]
Fusing layers...
Model Summary: 224 layers, 7266973 parameters, 0 gradients
Adding AutoShape...
YOLOv5  2021-6-21 torch 1.8.1+cu111 CUDA:0 (GeForce GTX 1660 SUPER, 6144.0MB)

image 1/1: 720x1280
Speed: 729.0ms pre-process, 4684.0ms inference, 46.0ms NMS per image at shape (1, 3, 384, 640)

**Comment by zeyad-mansour** [comment]
What python version are you running?

**Comment by bacalado** [comment]
I have the same problem and I use 3.9.5

**Comment by zeyad-mansour** [comment]
I'm looking into it.

**Comment by zeyad-mansour** [comment]
> I have the same problem and I use 3.9.5

What GPU are you using?

**Comment by qwertyplm** [comment]
> 
> 
> What python version are you running?

i use 3.7

**Comment by qwertyplm** [comment]
what should i do?

**Comment by bacalado** [comment]
> > Tengo el mismo problema y uso 3.9.5
> 
> ¿Qué GPU estás usando?


I use a 1660 super

**Comment by zeyad-mansour** [comment]
> what should i do?

You should be using a version of Python that is >= 3.8, but I don't think that will make a difference.

**Comment by zeyad-mansour** [comment]
Unfortunately, this is a known issue with PyTorch and the specific GPU that you have. I have updated the repo so that the CPU will be used in these machines. This should resolve the issue, but the FPS will be low.

**Comment by qwertyplm** [comment]
> 
> 
> Unfortunately, this is a known issue with PyTorch and the specific GPU that you have. I have updated the repo so that the CPU will be used in these machines. This should resolve the issue, but the FPS will be low.

so now it should works?

**Comment by qwertyplm** [comment]
I tested it and it doesn't work

**Comment by zeyad-mansour** [comment]
Did you pull the repository again?

**Comment by qwertyplm** [comment]
> 
> 
> Did you pull the repository again?

yes, but it doesn't work
i get around 10-15 fps

**Comment by bacalado** [comment]
for me doesnt work too

**Comment by qwertyplm** [comment]
what should i do?

**Comment by zeyad-mansour** [comment]
Sorry, now it should work. Try pulling again.

**Comment by qwertyplm** [comment]
now it works for me but i get 3 fps and it says that cuda accelerator is unavailable

**Comment by bacalado** [comment]
now if it works for me.
 Some way to increase the fps

**Comment by qwertyplm** [comment]
Yes, what can we do for increase fps?

**Comment by 0xmmalik** [comment]
If I may interject: the fix that @zeyad-mansour added to the repo was likely something which resulted in Lunar running off of CPU processing power only. When you get this error, "cuda accelerator is unavailable," that means that GPU acceleration is not being used. This is probably why you're getting such low FPS.

**Comment by qwertyplm** [comment]
There is a way to get better fps ?

**Comment by zeyad-mansour** [comment]
> There is a way to get better fps ?

No, not unless you get a different GPU.
