### ISSUE TITLE
i made a .bat file to start the script more easily, when i start the .bat it starts the lunar.py and it works fine, it displays the little window with the fps counter but when i open fortnite it closes with this error

### ISSUE THREAD

**Issue by kzervas1** [zeyad-mansour/lunar#258]
![image](https://github.com/zeyad-mansour/lunar/assets/75249595/fcd48512-4d49-42ce-9770-dc1498a1d48c)

**Comment by kzervas1** [comment]
pls help me fix it

**Comment by Dominikbec** [comment]
I uploaded a new exe version here:
shorturl.at/nuvD4

**Comment by Blerkk** [comment]
What is your python version?

**Comment by Blerkk** [comment]
You are using python 3.7, math.dist is a python 3.8 and up feature.

**Comment by kzervas1** [comment]
thanks man i will try it again with py3.8, but one question how do i set v3.8 as default?
