### ISSUE TITLE
Failed to execute script lunar

### ISSUE THREAD

**Issue by isvktt** [zeyad-mansour/Lunar#27]
how do I open the ''lunar'' without showing anything on the screen? I tried converting to .exe using pyinstaller and --noconsole so nothing appears on the screen, but when I open it I get the message ''Failed to execute lunar script''

**Comment by zeyad-mansour** [comment]
Converting to an executable file is not something that you're meant to do, but it's fairly simple. Refer to [this](https://www.geeksforgeeks.org/convert-python-script-to-exe-file/).
