### ISSUE TITLE
Low FPS

### ISSUE THREAD

**Issue by EchterAlsFake** [zeyad-mansour/Lunar#30]
I have only between 15 and 30 FPS but I have an Nvidia RTX 2070 Super OC.
Can you tell me why?
![Filme   TV 08 07 2021 19_42_55](https://user-images.githubusercontent.com/81284489/124967485-c6948a00-e024-11eb-8254-74529cdfecd0.png)

**Comment by zeyad-mansour** [comment]
That's strange. What's the refresh rate of your monitor?

**Comment by Quickburst** [comment]
I'm having the same issue with a GTX 1070. I can't think of many reasons, would it matter if the graphics card's resources are being overused?

**Comment by EchterAlsFake** [comment]
My monitor refresh rate is 60 too

**Comment by eseeseuwawa** [comment]
I have the same issue, 1650 Super, Also it doesnt seem to work

**Comment by eseeseuwawa** [comment]
![image](https://user-images.githubusercontent.com/35111227/125212284-4cf5d980-e27a-11eb-8a86-d59a8738c83b.png)
context, everything is installed

**Comment by zeyad-mansour** [comment]
Thanks for the descriptions.

One factor that increases the latency (or decreases the FPS) is the current method of screen capture. MSS only records the screen at the refresh rate of the monitor, so a 60hz monitor implies worse performance than a 240hz monitor. In addition to that, inference time can also be improved. See [future updates](https://github.com/zeyad-mansour/Lunar#future-updates). 

These are performance issues that I'll try to fix in an update later.

Nevertheless, a GTX 1070 and a 240hz monitor should get 60 - 90 FPS at the moment.

**Comment by zeyad-mansour** [comment]
> I have the same issue, 1650 Super, Also it doesnt seem to work

Do you mean that players are not being detected (like [this](https://github.com/zeyad-mansour/Lunar/issues/25))?

**Comment by eseeseuwawa** [comment]
@zeyad-mansour Yes, nothing is happening
