### ISSUE TITLE
mouse pointer runs to the top left corner

### ISSUE THREAD

**Issue by mrdamaia** [zeyad-mansour/Lunar#32]
Hi,

I`m trying to use it playing warzone. It targets my enemies but when I press the right mouse buttom the pointer runs to the top left corner of the screen. What am I doing wrong?

**Comment by smeush** [comment]
Hello, 

Looks like I have a similar problem in warzone, mine goes all the way down.  I've noticed that the targeting was acquiring the top of my weapon.  In my tests I had a XM4.  Any ideas on how to fix this ?

**Comment by zeyad-mansour** [comment]
I haven't tested it for warzone yet so it's likely that there are a few issues. I'll add support for these other games in the future.
