### ISSUE TITLE
CUDA ACCELERATION IS UNAVAILABLE

### ISSUE THREAD

**Issue by EdgarAldair** [zeyad-mansour/Lunar#33]
I have this problem CUDA ACCELERATION IS UNAVAILABLE (ISSUE WITH 1650/1660 GPUs)
![python](https://user-images.githubusercontent.com/34665443/125918731-561e6a3e-ce25-4d1d-8643-012c5b1152aa.png)

**Comment by zeyad-mansour** [comment]
See this [issue](https://github.com/zeyad-mansour/Lunar/issues/25).
