### ISSUE TITLE
Problem occure while pip install -r requirements.txt

### ISSUE THREAD

**Issue by ArkaIison** [zeyad-mansour/Lunar#35]
![image](https://user-images.githubusercontent.com/87036907/126208254-4690af6f-6b48-4eac-9d44-3189671d42b3.png)

**Comment by ArkaIison** [comment]
Also, how can i use it for warzone ?

**Comment by zeyad-mansour** [comment]
It appears that you are encountering this error due to the long install path.  To fix this, install a fresh version of Python and make sure to disable the MAX_PATH limitation during the installation process.

**Comment by zeyad-mansour** [comment]
> Also, how can i use it for warzone ?

It's not ready for warzone yet.
