### ISSUE TITLE
RuntimeError:Expected all tensors to be on same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by 1nteg3r** [zeyad-mansour/Lunar#36]

**Comment by 1nteg3r** [comment]
![image](https://user-images.githubusercontent.com/54937634/126506297-3a6a5964-3b25-4b35-9dba-2b9d41c0c756.png)

**Comment by zeyad-mansour** [comment]
Unfortunately, your GPU (GTX 1650) does not work with this project at the moment.
