### ISSUE TITLE
Mouse Movement in Valorant Not Working

### ISSUE THREAD

**Issue by FishyFishsEatingFishs** [zeyad-mansour/Lunar#38]
When ever i open valorant with the lunar screen capture thing on it closes down and shows this:

![Capture](https://user-images.githubusercontent.com/87787187/126571964-38410f13-369c-49e8-a777-165d152d5a5d.PNG)

**Comment by FishyFishsEatingFishs** [comment]
This also happens when i open up a fortnite character picture on google

**Comment by FishyFishsEatingFishs** [comment]
so its not cause of valorant

**Comment by FishyFishsEatingFishs** [comment]
Okay so i got it working by uninstalling everything to do with python including the registry's but the aimbot isnt locking on valorant like i didnt expect it to even target bots but it did, if its targeting on something why isnt the aimbot working does this have to do with the sensitivity because you made it compatible with fortnite?

**Comment by zeyad-mansour** [comment]
> Okay so i got it working by uninstalling everything to do with python including the registry's but the aimbot isnt locking on valorant like i didnt expect it to even target bots but it did, if its targeting on something why isnt the aimbot working does this have to do with the sensitivity because you made it compatible with fortnite?

I haven't installed or even looked at Valorant yet, so I can't address this issue at the moment. You should expect it to not work with games other than Fortnite.

**Comment by FishyFishsEatingFishs** [comment]
its prob because of move_crosshair its detected by valorant and they block it.

From what ive found the following is detected on valorant:
NtUserSendInput
SendInput
PostMessage
SendMessage
MouseEvent
InputInjector (GamePad / Pens / Touch)
CreateCursor
SetCursorPos
SetCursor
Moving cursor with uiAccess and self signed exe

However Arduino is not DETECTED but you need an Arduino

**Comment by FishyFishsEatingFishs** [comment]
they are gonna prob figure how to patch the Arduino method soon anyways

**Comment by zeyad-mansour** [comment]
> its prob because of move_crosshair its detected by valorant and they block it.
> 
> From what ive found the following is detected on valorant:
> NtUserSendInput
> SendInput
> PostMessage
> SendMessage
> MouseEvent
> InputInjector (GamePad / Pens / Touch)
> CreateCursor
> SetCursorPos
> SetCursor
> Moving cursor with uiAccess and self signed exe
> 
> However Arduino is not DETECTED but you need an Arduino

interesting. i doubt it though. i'm installing rn to test this.

**Comment by FishyFishsEatingFishs** [comment]
i think you can create a mouse driver HID driver (Human Interface Device) you can communicate with and simulate mouse movements from the driver But idk how to make it

**Comment by FishyFishsEatingFishs** [comment]
This person uses a raspberrypi-zero as the HID https://github.com/obtusecanadiangoose/valorant-aimbot

**Comment by zeyad-mansour** [comment]
I just tried it, and you are correct, the current method of mouse movement does not work. This will be a problem; however, as you mentioned, I'm sure there are many ways to bypass this. 

btw after looking at Valorant and comparing it to Fortnite I feel that external cheats have much more potential

**Comment by FishyFishsEatingFishs** [comment]
i think its possible to use a second pc as an hid but i only found this: https://stackoverflow.com/questions/28386160/setting-up-a-computer-to-act-as-an-hid-device-connected-to-another-computer-via

**Comment by zeyad-mansour** [comment]
this is very interesting. I'm going to need to read up on this.

**Comment by FishyFishsEatingFishs** [comment]
Ive got a question i dont really know much about yolo but from what i can see youre combining a bunch of player images into the best.pt file then using that to feed yolo?? is that how it works? how would i compile the images i gather into a pl file too?

**Comment by zeyad-mansour** [comment]
> Ive got a question i dont really know much about yolo but from what i can see youre combining a bunch of player images into the best.pt file then using that to feed yolo?? is that how it works? how would i compile the images i gather into a pl file too?

check out the repo.

**Comment by mindz0r** [comment]
this wroks on csgo?

**Comment by zeyad-mansour** [comment]
> this wroks on csgo?

not yet

**Comment by soulxd477** [comment]
how you run it?
