### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HELLOWORLD1060** [zeyad-mansour/Lunar#39]
Hello,i have error,can you help me plz.......
![rhbgvfcde](https://user-images.githubusercontent.com/87854906/126762596-3443a5f5-b220-42aa-b942-6257313e151a.PNG)

**Comment by zeyad-mansour** [comment]
What version of python are you running?

**Comment by revolexGeek** [comment]
Use python 3.8+.
math.dist module isnt available on 3.8- python versions.
