### ISSUE TITLE
error on run

### ISSUE THREAD

**Issue by moaji** [zeyad-mansour/Lunar#4]
![image_2021-05-14_173026](https://user-images.githubusercontent.com/69601126/118342828-13069200-b4da-11eb-8769-6691198d0280.png)

**Comment by Ares1944** [comment]
it is because you are monkey

**Comment by moaji** [comment]
cope

**Comment by Ares1944** [comment]
no u nn

**Comment by moaji** [comment]
cry ab it faNN

**Comment by zeyad-mansour** [comment]
What python version are you running?
`python --version`
