### ISSUE TITLE
Aimbot Training

### ISSUE THREAD

**Issue by damagedd** [zeyad-mansour/Lunar#44]
The aimbot works great, love your script.  I have been training my own models for games.  One of the issues I have is I get an increase in false positive detections with my models.  Any good tips on what types of screenshots to use?  I use a mix of clean and messy images.  Thinking the messy images may be causing the conflicts.  I use around 1500 images, is that too many or too few for the yolov5s model?  Any tips would be greatly appreciated.  cheers!

**Comment by damagedd** [comment]
Do you use Roboflow to build your training sets?  Perhaps we can collaborate?

**Comment by zeyad-mansour** [comment]
> Do you use Roboflow to build your training sets?  Perhaps we can collaborate?

@damagedd My discord is xerox#6605. Feel free to contact me there.
