### ISSUE TITLE
Error when running on linux

### ISSUE THREAD

**Issue by nb850** [zeyad-mansour/Lunar#45]
When I try to run python3 lunar.py I get an error -

Traceback (most recent call last):
  File "lunar.py", line 6, in <module>
    from pynput import keyboard
ModuleNotFoundError: No module named 'pynput'

**Comment by revolexGeek** [comment]
Try to: `pip install -r requirements.txt`

**Comment by nb850** [comment]
I get error - 
![129482738-435b25de-aefc-415e-8f49-3e4a292c7661](https://user-images.githubusercontent.com/88045270/129485322-920cf404-1790-4ada-ac5c-4477367a8215.png)

**Comment by zeyad-mansour** [comment]
correct. you cannot run the program on linux.
