### ISSUE TITLE
I get an error

### ISSUE THREAD

**Issue by dantepassone** [zeyad-mansour/Lunar#49]
I have already installed the necessary dependencies using pip
I have python 3.8 and cuda 11.1 installed.

Traceback (most recent call last):
  File "lunar.py", line 74, in <module>
    main()
  File "lunar.py", line 21, in main
    lunar = Aimbot(collect_data = "collect_data" in sys.argv, controller = "controller" in sys.argv)
TypeError: __init__() got an unexpected keyword argument 'controller'
![image](https://user-images.githubusercontent.com/31426553/130682053-f4014eb8-4dfa-4cad-9138-10b7edb27f6f.png)

I also tried with the latest version of python

update: I downloaded an old version of Lunar and it worked correctly.

**Comment by jwjw2069** [comment]
what version u using?

**Comment by zeyad-mansour** [comment]
> I have already installed the necessary dependencies using pip
> I have python 3.8 and cuda 11.1 installed.
> 
> Traceback (most recent call last):
> File "lunar.py", line 74, in
> main()
> File "lunar.py", line 21, in main
> lunar = Aimbot(collect_data = "collect_data" in sys.argv, controller = "controller" in sys.argv)
> TypeError: **init**() got an unexpected keyword argument 'controller'
> ![image](https://user-images.githubusercontent.com/31426553/130682053-f4014eb8-4dfa-4cad-9138-10b7edb27f6f.png)
> 
> I also tried with the latest version of python
> 
> update: I downloaded an old version of Lunar and it worked correctly.

yes, controller is not supported in the latest commit.
