### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jwjw2069** [zeyad-mansour/Lunar#50]
[!] Sensitivity configuration is not set
[INFO] In-game X and Y axis sensitivity should be the same
X-Axis and Y-Axis Sensitivity (from in-game settings): 22
Targeting Sensitivity (from in-game settings): 50
[INFO] Your in-game targeting sensitivity must be the same as your scoping sensitivity
[INFO] Sensitivity configuration complete
Traceback (most recent call last):
  File "lunar.py", line 74, in <module>
    main()
  File "lunar.py", line 21, in main
    lunar = Aimbot(collect_data = "collect_data" in sys.argv, controller = "controller" in sys.argv)
TypeError: __init__() got an unexpected keyword argument 'controller'

**Comment by zeyad-mansour** [comment]
controller is not supported
