### ISSUE TITLE
controller?

### ISSUE THREAD

**Issue by jwjw2069** [zeyad-mansour/Lunar#51]
Traceback (most recent call last):
  File "lunar.py", line 74, in <module>
    main()
  File "lunar.py", line 21, in main
    lunar = Aimbot(collect_data = "collect_data" in sys.argv, controller = "controller" in sys.argv)
TypeError: __init__() got an unexpected keyword argument 'controller'

but im not using controller neither do  i have one plugged in

**Comment by zeyad-mansour** [comment]
oh, I understand the issue now. thanks for clarifying. this issue has been resolved.
