### ISSUE TITLE
i can't install pytorch

### ISSUE THREAD

**Issue by anonio100** [zeyad-mansour/Lunar#6]
Collecting torchvision
  Using cached torchvision-0.9.1-cp38-cp38-win_amd64.whl (852 kB)
Requirement already satisfied: numpy in c:\users\caler\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from torchvision) (1.20.3)
Requirement already satisfied: pillow>=4.1.1 in c:\users\caler\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from torchvision) (8.2.0)
Collecting torch==1.8.1
  Using cached torch-1.8.1-cp38-cp38-win_amd64.whl (190.5 MB)
Requirement already satisfied: typing-extensions in c:\users\caler\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from torch==1.8.1->torchvision) (3.10.0.0)
Installing collected packages: torch, torchvision
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\caler\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\\caffe2\\python\\serialized_test\\data\\operator_test\\collect_and_distribute_fpn_rpn_proposals_op_test.test_collect_and_dist.zip'

**Comment by zeyad-mansour** [comment]
Try installing a fresh Python 3.7 version and make sure to disable the MAX_PATH limitation during the installation process. That may be why you are encountering that error.

I will be updating the repo in a few days; that should fix a few issues caused by Python 3.8+ versions.

**Comment by anonio100** [comment]
Traceback (most recent call last):
  File "lunar.py", line 6, in <module>
    from lib.aimbot import Aimbot
  File "C:\Users\caler\Desktop\Lunar-main\lib\aimbot.py", line 10, in <module>
    import win32api
ImportError: DLL load failed:

**Comment by anonio100** [comment]
Thank you very much but now I have got this error


Traceback (most recent call last):
  File "lunar.py", line 6, in <module>
    from lib.aimbot import Aimbot
  File "C:\Users\caler\Desktop\Lunar-main\lib\aimbot.py", line 10, in <module>
    import win32api
ImportError: DLL load failed:

**Comment by anonio100** [comment]
Thank you

But what is the probability that I get banned??

**Comment by zeyad-mansour** [comment]
No problem. You won't get banned since it's fully external.
However, I would consider this project right now as proof of idea, so it's not that practical to use right now. It's still in its early stages, and there are several things that I am working on to make this much better.
