### ISSUE TITLE
unable to draw the bounding boxes?

### ISSUE THREAD

**Issue by toomttrr** [zeyad-mansour/Lunar#7]
```
   cv2.rectangle(frame, x1y1, x2y2, [0, 0, 255], 2) #draw the bounding boxes
cv2.error: OpenCV(4.5.2) :-1: error: (-5:Bad argument) in function 'rectangle'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'rec'. Expected sequence length 4, got 2
>  - Can't parse 'rec'. Expected sequence length 4, got 2
```

**Comment by zeyad-mansour** [comment]
That error arises when OpenCV is installed with Python 3.8+ as the rectangle function does not accept float tensors.

You can resolve that by installing Python 3.7, or I suggest waiting until I update this repo in a few days. Then, you can pull again.

**Comment by toomttrr** [comment]
> 
> 
> That error arises when OpenCV is installed with Python 3.8+ as the rectangle function does not accept float tensors.
> 
> You can resolve that by installing Python 3.7, or I suggest waiting until I update this repo in a few days. Then, you can pull again.

Thank you for the fast reply. I did go ahead and install 3.7 but i'm not sure how to run it in VS Code using 3.7 and not 3.9? Thanks again.

**Comment by zeyad-mansour** [comment]
I do not use VS Code, but I would assume there is a way to use different interpreters.
Rather than using VS Code, you could install Python 3.7 directly (add it to PATH) and run directly from the CLI.

**Comment by toomttrr** [comment]
I tried with only having 3.7 installed and it gave me the same error. 
`(Overload resolution)` 
Is that something to do with the actual resolution of the screen? It seems like opencv is the culprit at least.

I'm super new to Python but having projects like this to work through and diagnose is hella fun compared to an book! (For me).

**Comment by zeyad-mansour** [comment]
Thanks for letting me know of this issue, I'll fix it in the next update.
