### ISSUE TITLE
Help With the snapping / locking on

### ISSUE THREAD

**Issue by uhhdexz** [zeyad-mansour/lunar#75]
Hello, ima give you  a quick brief of what's going on when I right click / aim in its supposed to lock on  via the snap line, but when I right click it moves my mouse a away from the target I already trained it. Maybe I have to install something or fix my path idk I jus need help. 

If you want comment your answer here or if you wanna go through the setup with me add me on discord Dexz#1652

**Comment by iHafez** [comment]
just download cuda

**Comment by GreenNightfall** [comment]
> Hello, ima give you a quick brief of what's going on when I right click / aim in its supposed to lock on via the snap line, but when I right click it moves my mouse a away from the target I already trained it. Maybe I have to install something or fix my path idk I jus need help.
> 
> If you want comment your answer here or if you wanna go through the setup with me add me on discord Dexz#1652

Could you solve the problem?
